config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
    resources :posts do
      resources :comments
    end

    root 'posts#index', as: 'post/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :user_id, presence: true
  belongs_to :user
  validates :image, presence: true
  has_many :comments, dependent: :destroy

  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }
  has_many :comments, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :set_post

    def create
      @comment = @post.comments.new(comment_params)
      @comment.user_id = current_user.id

      if @comment.save
        respond_to do |format|
        format.html { redirect_to post_index_path }
        format.js
        end
      else
        flash[:alert] = "Check the comment form, something went horribly wrong."
        render post_index_path
      end
    end


    def destroy
      @comment = @post.comments.find(params[:id])

      if @comment.user_id == current_user.id
        @comment.delete
        respond_to do |format|
          format.html { redirect_to root_path }
          format.js
        end
      end
    end


  private

  def comment_params
  params.require(:comment).permit(:content)
  end

  def set_post
  @post = Post.find(params[:post_id])
  end




end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :owned_post, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = current_user.posts.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = "Your post has been created!"
    else
      flash[:alert] = "Your new post couldn't be created!  Please check the form."
      render :new
    end
    redirect_to posts_path
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    if @post = Post.find(params[:id])
    flash[:success] = "Post updated."
    @post.update(post_params)
    redirect_to(post_path(@post))
    flash.now[:alert] = "Update failed.  Please check the form."
    else
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

private

  def post_params
    params.require(:post).permit(:image, :caption)
  end

  def owned_post
    @post = Post.find(params[:id])
    unless current_user == @post.user
    flash[:alert] = "That post doesn't belong to you!"
    redirect_to post_index_path
    end
  end


end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="user-name">
  <%= comment.user.user_name %>
</div>
<div class="comment-content">
  <%= comment.content %>
</div>
<% if comment.user == current_user %>
  <%= link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" }, :remote => true do %>
  <i class="fas fa-trash-alt fa-2x" style="padding: 5px; float: right; margin-top: -36px;"></i>
<% end %>
<% end %>

app/views/comments/create.js.erb
$('#comments_<%= @post.id %>').append("<%=j render 'comments/comment', post: @post, comment: @comment %>");
$('#comment_content_<%= @post.id %>').val('')

app/views/comments/destroy.js.erb
$('#comments_<%= @post.id %>').html("<%= j render @post.comments, post: @post, comment: @comment %>");

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "ArthurGram", post_index_path, class: 'navbar-brand' %>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li><%= link_to "Edit Profile", edit_user_registration_path  %></li>
        <li><%= link_to "Upload Photos", new_post_path %></li>
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to "Sign Up", new_user_registration_path  %></li>
        <li><%= link_to "Log In", new_user_session_path  %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
    <title><%= content_for?(:title) ? yield(:title) : "ArthurGram" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>



    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

<%= render 'layouts/navbar' %>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
        </div><!--/span-->
      </div><!--/row-->


    </div> <!-- /container -->


    <footer>
      <p>&copy; Company 2018</p>
    </footer>

  </body>
</html>

app/views/posts/_form.html.erb
<%= simple_form_for @post do |f| %>
  <%= f.input :image %>
  <%= f.input :caption %>
  <%= f.button :submit %>
<% end %>

app/views/posts/_post.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-head">
      <div class="thumb-img"></div>
      <div class="user-name">
        <%= post.user.user_name %>
      </div>
    </div>
    <div class="image center-block">
      <%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
    </div>
    <div class="post-bottom">
      <div class="caption">
        <div id="user_unique" style="
    font-weight: 700;
">
          <%= post.user.user_name %>
        </div>
        <div class="caption-content">
          <%= post.caption %>
        </div>
        <div class="comments" id="comments_<%= post.id %>">
          <% if post.comments %>
            <%= render post.comments, post: post %>
          <% end %>
        </div>
      </div>

    </div>
    <div class="comments" id="comments_<%= post.id %>"></div>
    <div class="comment-like-form row">
      <div class="like-button col-sm-1">
        <i class="far fa-heart fa-2x"></i>
        <div class="comment-form col-sm-11">
          <%= simple_form_for([post, post.comments.new], :remote => true) do |f| %>
          <%= f.text_field :content, class: 'arthur_form', placeholder: 'Add a comment...' %>
          <%= f.button :submit, class: "btn btn-primary padding: 50px;" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="time_ago">
    <%= time_ago_in_words post.created_at %> ago
  </div>

app/views/posts/edit.html.erb
<div class="text-center">
  <%= image_tag @post.image.url(:medium) %>
</div>
<div class="form-wrapper">
  <%= simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f| %>
    <div class="form-group">
      <%= f.input :image %>
    </div>
    <div class="form-group text-center">
      <%= f.input :caption %>
    </div>
    <div class="form-group text-center">
      <%= f.button :submit, class: 'btn-success' %>
    </div>
  <% end %>
</div>
<div class="text-center edit-links">
  <%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
  |
  <%= link_to "cancel", posts_path %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>

  <%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="posts-wrapper row">
  <div class="post">
    <div class="post-head">
      <div class="name">
        <%= @post.user.user_name %>
      </div>
    </div>
    <div class="image center-block">
      <%= image_tag @post.image.url(:medium) %>
    </div>
    <p class="caption">
      <%= @post.caption %>
    </p>
  </div>
  <div class="text-center edit-links">

  <% if @post.user_id == current_user.id %>
  <%= link_to "Cancel", posts_path %>
  |
  <%= link_to "Edit Post", edit_post_path(@post) %>
  <% else %>
  <%= link_to "Cancel", posts_path %>
<% end %>

  </div>
</div>